export const BOOK_CATEGORIES = [
  'Fiction',
  'Non-Fiction',
  'Fantasy',
  'Sci-Fi',
  'Thriller',
  'Horror',
  'Romance',
  'Mystery',
  'Biography',
  'History',
  'Poetry',
  'Comics',
  'Art',
  'Cookbooks',
  'Journals',
  'Prayer books',
  'Series',
  'Encyclopedias',
  'Dictionaries',
  'Self-help books',
  'Health books',
  'Travel books',
  'Guide books',
  "Children's books",
  'Young adult fiction',
  'Diaries',
  'Trilogy',
  'Autobiographies',
  'Almanacs',
  'Atlases',
  'Textbooks',
  'Magazines',
  'Newspapers',
  'Religious books',
  'Other',
];

export const SNACKBARTIMEOUT = 5000;
export const DEFAULT_COVER_IMAGE_URL =
  'https://img.freepik.com/premium-vector/hand-drawn-world-book-day-concept_23-2148481516.jpg?size=250&ext=jpg&ga=GA1.1.1413502914.1696550400&semt=ais';
