export const BOOK_CATEGORIES = [
  'Fiction',
  'Non-Fiction',
  'Fantasy',
  'Sci-Fi',
  'Thriller',
  'Horror',
  'Romance',
  'Mystery',
  'Biography',
  'History',
  'Poetry',
  'Comics',
  'Art',
  'Cookbooks',
  'Journals',
  'Prayer books',
  'Series',
  'Encyclopedias',
  'Dictionaries',
  'Self-help books',
  'Health books',
  'Travel books',
  'Guide books',
  "Children's books",
  'Young adult fiction',
  'Diaries',
  'Trilogy',
  'Autobiographies',
  'Almanacs',
  'Atlases',
  'Textbooks',
  'Magazines',
  'Newspapers',
  'Religious books',
  'Other',
];


export const SNACKBARTIMEOUT = 5000;
